apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::527371517066:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-17FMU0TDWF818
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::527371517066:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-10T14:00:48Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "5009"
  uid: d7dd633d-0222-4aaa-a61a-5cc9665e18b9
