apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::527371517066:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-32O0YYD4BX9G
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::527371517066:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-10T06:30:34Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1476"
  uid: 2ecfb6d9-62eb-456e-b4b1-362f4a9da63b
